In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
import numpy as np
import pandas as pd

In [6]:
df = pd.read_csv("/content/drive/MyDrive/students.csv")

### **Create the DataFrame from the table above. Display: shape, columns, dtypes, head(5), and tail(3).**

In [7]:
df.shape

(10, 8)

In [8]:
df.columns

Index(['StudentID', 'Name', 'Age', 'City', 'Department', 'Score', 'Grade',
       'Passed'],
      dtype='object')

In [9]:
df.dtypes

StudentID      int64
Name          object
Age            int64
City          object
Department    object
Score          int64
Grade         object
Passed          bool
dtype: object

In [10]:
df.head()

   StudentID          Name  Age     City Department  Score Grade  Passed
0       5001   Arjun Mehta   21    Delhi        CSE     78     B    True
1       5002  Divya Sharma   22   Mumbai        ECE     91     A    True
2       5003   Karan Patel   20     Pune        CSE     65     C    True
3       5004    Meera Nair   23  Chennai       MECH     42     D    True
4       5005   Sahil Gupta   21    Delhi        ECE     88     A    True

In [11]:
df.tail()

   StudentID           Name  Age     City Department  Score Grade  Passed
5       5006   Anjali Singh   22   Jaipur        CSE     35     F   False
6       5007    Rohan Verma   20   Mumbai       MECH     67     B    True
7       5008    Pooja Yadav   23  Chennai        CSE     92     A    True
8       5009    Vivek Kumar   21     Pune        ECE     71     B    True
9       5010  Nisha Agarwal   22    Delhi       MECH     58     C    True

### **Run df.info() and df.describe(). From describe(): what is the mean Score? What is the standard deviation?**

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudentID   10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   City        10 non-null     object
 4   Department  10 non-null     object
 5   Score       10 non-null     int64
 6   Grade       10 non-null     object
 7   Passed      10 non-null     bool
dtypes: bool(1), int64(3), object(4)
memory usage: 702.0+ bytes

In [13]:
df.describe()

        StudentID        Age      Score
count    10.00000  10.000000  10.000000
mean   5005.50000  21.500000  68.700000
std       3.02765   1.080123  19.675422
min    5001.00000  20.000000  35.000000
25%    5003.25000  21.000000  59.750000
50%    5005.50000  21.500000  69.000000
75%    5007.75000  22.000000  85.500000
max    5010.00000  23.000000  92.000000

### **Access the 'Name' column using df['Name']. Then access 'Score' and 'Grade' columns together using double brackets.**

In [14]:
df["Name"]

0      Arjun Mehta
1     Divya Sharma
2      Karan Patel
3       Meera Nair
4      Sahil Gupta
5     Anjali Singh
6      Rohan Verma
7      Pooja Yadav
8      Vivek Kumar
9    Nisha Agarwal
Name: Name, dtype: object

In [15]:
df[["Score", "Grade"]]

   Score Grade
0     78     B
1     91     A
2     65     C
3     42     D
4     88     A
5     35     F
6     67     B
7     92     A
8     71     B
9     58     C

### **Use df.loc to select: (a) row at index 0, (b) rows 2 to 5, (c) rows 0–4 but only columns Name, Score, Grade.**

### **Use df.iloc to select: (a) first 3 rows, (b) last 2 rows, (c) rows at positions 1, 3, 5 and columns at positions 0, 2, 4.**

In [19]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/students.csv")

# (a) First 3 rows
display(df.iloc[:3])

   StudentID          Name  Age    City Department  Score Grade  Passed
0       5001   Arjun Mehta   21   Delhi        CSE     78     B    True
1       5002  Divya Sharma   22  Mumbai        ECE     91     A    True
2       5003   Karan Patel   20    Pune        CSE     65     C    True

In [17]:
# (b) Last 2 rows
display(df.iloc[-2:])

   StudentID           Name  Age   City Department  Score Grade  Passed
8       5009    Vivek Kumar   21   Pune        ECE     71     B    True
9       5010  Nisha Agarwal   22  Delhi       MECH     58     C    True

In [18]:
# (c) Rows at positions 1, 3, 5 and columns at positions 0, 2, 4
display(df.iloc[[1, 3, 5], [0, 2, 4]])

   StudentID  Age Department
1       5002   22        ECE
3       5004   23       MECH
5       5006   22        CSE

### **Q6 [Boolean Filter] Filter students where Score > 80. How many students scored above 80?**

In [20]:
high_score_students = df[df['Score'] > 80]
display(high_score_students)
print(f"Number of students who scored above 80: {len(high_score_students)}")

   StudentID          Name  Age     City Department  Score Grade  Passed
1       5002  Divya Sharma   22   Mumbai        ECE     91     A    True
4       5005   Sahil Gupta   21    Delhi        ECE     88     A    True
7       5008   Pooja Yadav   23  Chennai        CSE     92     A    True

Number of students who scored above 80: 3

### **Q7 [Boolean Filter] Filter students from Delhi who are in CSE department.**

In [21]:
delhi_cse_students = df[(df['City'] == 'Delhi') & (df['Department'] == 'CSE')]
display(delhi_cse_students)

   StudentID         Name  Age   City Department  Score Grade  Passed
0       5001  Arjun Mehta   21  Delhi        CSE     78     B    True

In [22]:
delhi_cse_students_selected_cols = delhi_cse_students[['Name', 'Score', 'Grade']]
display(delhi_cse_students_selected_cols)

          Name  Score Grade
0  Arjun Mehta     78     B

### **Q8 [Boolean Filter] Find all students who Failed (Passed == False). What is their average Score?**

In [23]:
failed_students = df[df['Passed'] == False]
display(failed_students)

average_score_failed = failed_students['Score'].mean()
print(f"Average score of students who failed: {average_score_failed:.2f}")

   StudentID          Name  Age    City Department  Score Grade  Passed
5       5006  Anjali Singh   22  Jaipur        CSE     35     F   False

Average score of students who failed: 35.00

### **Q9 [String Filter] Filter students whose Name contains the string 'a' (case-insensitive) using .str.contains().**

In [24]:
students_with_a_in_name = df[df['Name'].str.contains('a', case=False, na=False)]
display(students_with_a_in_name)

   StudentID           Name  Age     City Department  Score Grade  Passed
0       5001    Arjun Mehta   21    Delhi        CSE     78     B    True
1       5002   Divya Sharma   22   Mumbai        ECE     91     A    True
2       5003    Karan Patel   20     Pune        CSE     65     C    True
3       5004     Meera Nair   23  Chennai       MECH     42     D    True
4       5005    Sahil Gupta   21    Delhi        ECE     88     A    True
5       5006   Anjali Singh   22   Jaipur        CSE     35     F   False
6       5007    Rohan Verma   20   Mumbai       MECH     67     B    True
7       5008    Pooja Yadav   23  Chennai        CSE     92     A    True
8       5009    Vivek Kumar   21     Pune        ECE     71     B    True
9       5010  Nisha Agarwal   22    Delhi       MECH     58     C    True

### **Q10 [Add Column] Add a new column 'Score_Category': if Score >= 80 → 'Distinction', Score >= 60 → 'Merit', else 'Pass/Fail'. Use np.where() or nested condition.**

In [25]:
df['Score_Category'] = np.where(df['Score'] >= 80, 'Distinction',
                                np.where(df['Score'] >= 60, 'Merit', 'Pass/Fail'))
display(df.head()) # Display the first few rows to show the new column

,StudentID,Name,Age,City,Department,Score,Grade,Passed,Score_Category
0,5001,Arjun Mehta,21,Delhi,CSE,78,B,True,Merit
1,5002,Divya Sharma,22,Mumbai,ECE,91,A,True,Distinction
2,5003,Karan Patel,20,Pune,CSE,65,C,True,Merit
3,5004,Meera Nair,23,Chennai,MECH,42,D,True,Pass/Fail
4,5005,Sahil Gupta,21,Delhi,ECE,88,A,True,Distinction

### **Sort the DataFrame by Score in descending order.**

In [26]:
df_sorted = df.sort_values(by='Score', ascending=False)
display(df_sorted.head())

,StudentID,Name,Age,City,Department,Score,Grade,Passed,Score_Category
7,5008,Pooja Yadav,23,Chennai,CSE,92,A,True,Distinction
1,5002,Divya Sharma,22,Mumbai,ECE,91,A,True,Distinction
4,5005,Sahil Gupta,21,Delhi,ECE,88,A,True,Distinction
0,5001,Arjun Mehta,21,Delhi,CSE,78,B,True,Merit
8,5009,Vivek Kumar,21,Pune,ECE,71,B,True,Merit

### **Reset the index.**

In [27]:
df_sorted_reset = df_sorted.reset_index(drop=True)
display(df_sorted_reset.head())

,StudentID,Name,Age,City,Department,Score,Grade,Passed,Score_Category
0,5008,Pooja Yadav,23,Chennai,CSE,92,A,True,Distinction
1,5002,Divya Sharma,22,Mumbai,ECE,91,A,True,Distinction
2,5005,Sahil Gupta,21,Delhi,ECE,88,A,True,Distinction
3,5001,Arjun Mehta,21,Delhi,CSE,78,B,True,Merit
4,5009,Vivek Kumar,21,Pune,ECE,71,B,True,Merit

### **Show the top 5 students.**

In [28]:
top_5_students = df_sorted_reset.head(5)
display(top_5_students)

,StudentID,Name,Age,City,Department,Score,Grade,Passed,Score_Category
0,5008,Pooja Yadav,23,Chennai,CSE,92,A,True,Distinction
1,5002,Divya Sharma,22,Mumbai,ECE,91,A,True,Distinction
2,5005,Sahil Gupta,21,Delhi,ECE,88,A,True,Distinction
3,5001,Arjun Mehta,21,Delhi,CSE,78,B,True,Merit
4,5009,Vivek Kumar,21,Pune,ECE,71,B,True,Merit